apps/cart/urls.py
from django.conf.urls import url,include
from cart.views import CartAddView,CartInfoView,CartUpdateView,CartDeleteView


app_name='[cart]'
urlpatterns = [
    url(r'^add$', CartAddView.as_view(), name='add'),#添加购物车
    url('^update$', CartUpdateView.as_view(), name='update'),#更新购物车信息
    url('^delete$', CartDeleteView.as_view(), name='delete'),#删除
    url(r'^$',CartInfoView.as_view(),name='show'),#显示购物车信息

]

apps/goods/urls.py
from django.conf.urls import url,include
from goods.views import *

app_name='[goods]'
urlpatterns = [
    url(r'^index$', IndexView.as_view(), name='index'),  # 首页
    url(r'^goods/(?P<goods_id>\d+)$', DetailView.as_view(), name='detail'), # 详情页
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$', ListView.as_view(), name='list'),  # 列表页
]

apps/user/urls.py
from django.conf.urls import url
from user import views
from apps.user.views import *

app_name='[user]'

urlpatterns = [
    # url(r'^register$',views.register,name='register'),
    # url(r'^register_handle$',views.register_handle,name='register_handle'),
    url(r'^register$',RegisterView.as_view(),name='register'),#注册as_view返回函数引用，根据请求方法匹配不同的函数
    url(r'^active/(?P<token>.*)$',ActiveView.as_view(),name='active'),#激活
    url(r'^login$', LoginView.as_view(), name='login'),  # 登录
    url(r'^order/(?P<page>\d+)$',UserOrderView.as_view(),name='order'),#订单
    url(r'^address$',AddressView.as_view(),name='address'),#地址
    url(r'^$',UserInfoView.as_view(),name='user'),#信息
    url(r'^logout$', LogoutView.as_view(), name='logout'),  # 注销登录
]

dayfreshnew/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include


urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^user/',include('user.urls',namespace='user')),#用户模块
    url(r'^cart/',include('cart.urls',namespace='cart')),
    url('search/', include('haystack.urls')),# 全文检索框架
    url(r'^order/',include('order.urls',namespace='order')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^', include('goods.urls',namespace='goods')), #放在最后匹配首页

]

apps/cart/models.py
from django.db import models

# Create your models here.

apps/cart/views.py
from django.shortcuts import render
from django.http import JsonResponse
from django.shortcuts import render

# Create your views here.
from django.views import View
from django_redis import get_redis_connection

from goods.models import GoodsSKU
from utils.Mixin import LoginRequiredMixin

# Create your views here.
class CartAddView(View):
    """购物车记录添加"""

    def post(self, request):
        # 接受数据
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据验证
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目格式错误'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist as e:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 添加购物车记录, redis购物车使用的是hash类型保存的，用到hget获取key中的字典
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id
        cart_count = conn.hget(cart_key, sku_id)

        if cart_count:
            count += int(cart_count)


        # 验证商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # sku_id存在即更新，不存在则新建
        conn.hset(cart_key, sku_id, count)

        # 获取购物车的数量
        total_count = conn.hlen(cart_key)

        # 返回应答
        return JsonResponse({'res': 5, 'total_count': total_count, 'errmsg': '添加成功'})



class CartInfoView(LoginRequiredMixin, View):
    """购物车页面"""
    def get(self, request):

        # 获取登录的用户
        user = request.user

        # redis获取用户购物车信息
        conn = get_redis_connection('default')
        cart_key = 'cart_%s' % user.id
        cart_dict = conn.hgetall(cart_key)

        skus = []
        total_count = 0
        total_price = 0

        for sku_id, count in cart_dict.items():
            # 根据商品id查询商品信息
            sku = GoodsSKU.objects.get(id=sku_id)
            # 计算商品的单价
            amount = sku.price * int(count)
            # 动态给sku添加属性
            sku.amount = int(amount)
            sku.count = int(count)
            # 添加到列表
            skus.append(sku)

            total_count += int(count)
            total_price += int(amount)

        context = {
            'skus': skus,
            'total_count': total_count,
            'total_price': total_price,
        }

        return render(request, 'cart.html', context)

class CartUpdateView(View):
    """购物车列表更新商品的数量"""
    def post(self, request):
        # 接受数据
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        sku_id = request.POST.get('sku_id')
        count = request.POST.get('count')

        # 数据验证
        if not all([sku_id, count]):
            return JsonResponse({'res': 1, 'errmsg': '数据不完整'})

        try:
            count = int(count)
        except Exception as e:
            return JsonResponse({'res': 2, 'errmsg': '商品数目格式错误'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist as e:
            return JsonResponse({'res': 3, 'errmsg': '商品不存在'})

        # 更新购物车数量
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # 验证商品的库存
        if count > sku.stock:
            return JsonResponse({'res': 4, 'errmsg': '商品库存不足'})

        # sku_id存在即更新，不存在则新建
        conn.hset(cart_key, sku_id, count)

        # 返回应答
        return JsonResponse({'res': 5, 'errmsg': '更新成功'})


class CartDeleteView(View):
    """购物车记录删除"""
    def post(self, request):
        # 接受数据
        user = request.user
        if not user.is_authenticated:
            return JsonResponse({'res': 0, 'errmsg': '请先登录'})

        sku_id = request.POST.get('sku_id')

        # 数据验证
        if not sku_id:
            return JsonResponse({'res': 1, 'errmsg': '无效的商品id'})

        try:
            sku = GoodsSKU.objects.get(id=sku_id)
        except GoodsSKU.DoesNotExist as e:
            return JsonResponse({'res': 2, 'errmsg': '商品不存在'})

        # 更新购物车数量
        conn = get_redis_connection('default')
        cart_key = 'cart_%d' % user.id

        # sku_id存在即更新，不存在则新建
        conn.hdel(cart_key, sku_id)

        # 返回应答
        return JsonResponse({'res': 3, 'message': '删除成功'})

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{%  load staticfiles %}
{#首页  登录 注册#}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
{#标题块#}
	<title>{%  block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{#网页顶部引入文件块#}
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>
{#网页顶部欢迎信息块 #}
{% block head_con %}
	<div class="header_con">

		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{user.username}}</em>
                     <span>|</span>
					<a href="{%  url 'user:logout'%}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{%  url 'user:login'%}">登录</a>
					<span>|</span>
					<a href="{%  url 'user:register'%}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{%  url 'user:user'%}">用户中心</a>
					<span>|</span>
					<a href="/cart">我的购物车</a>
					<span>|</span>
					<a href="{%  url 'user:order' 1%}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{%  endblock head_con %}
{#网页顶部搜索框#}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="/cart/" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock search_bar %}
{#网页主体内容块#}
{% block body %}{% endblock body %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{#网页底部html元素块#}
    {% block bottom %}{% endblock bottom %}
{#网页底部代码块#}
    {% block bottomfiles %}{% endblock bottomfiles %}

</body>
</html>

templates/basedetaillist.html
{% extends 'base.html' %}
{#详情列表#}
{% block body %}
        <div class="navbar_con">
                <div class="navbar clearfix">
                    <div class="subnav_con fl">
                        <h1>全部商品分类</h1>
                        <span></span>
                        <ul class="subnav">
                            <li><a href="#" class="fruit">新鲜水果</a></li>
                            <li><a href="#" class="seafood">海鲜水产</a></li>
                            <li><a href="#" class="meet">猪牛羊肉</a></li>
                            <li><a href="#" class="egg">禽类蛋品</a></li>
                            <li><a href="#" class="vegetables">新鲜蔬菜</a></li>
                            <li><a href="#" class="ice">速冻食品</a></li>
                        </ul>
                    </div>
                    <ul class="navlist fl">
                        <li><a href="">首页</a></li>
                        <li class="interval">|</li>
                        <li><a href="">手机生鲜</a></li>
                        <li class="interval">|</li>
                        <li><a href="">抽奖</a></li>
                    </ul>
                </div>
            </div>

    {#    详情页和列表页的主体#}
    {% block main_content %}{% endblock main_content %}
{% endblock body %}


{% block botoomfiles %}{% endblock botoomfiles %}

templates/basenocart.html
{% extends 'base.html' %}
{% load staticfiles %}
{#购物车 用户中心 提交订单#}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}{% endblock page_title %}</div>
		<div class="search_con fr">
			<form method="get" action="/search">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
	</div>
{% endblock search_bar %}

templates/baseusercenter.html
{% extends 'basenocart.html' %}
{% block title %}天天生鲜-用户中心{% endblock title %}
{% block page_title %}用户中心{% endblock page_title %}
{% block body %}
    <div class="main_con clearfix">
            <div class="left_menu_con clearfix">
                <h3>用户中心</h3>
                <ul>
                    <li><a href="{% url 'user:user' %}" {% if page == 'user' %}class="active"{% endif %}>· 个人信息</a></li>
                    <li><a href="{% url 'user:order' 1%}"  {% if page == 'order' %}class="active"{% endif %}>· 全部订单</a></li>
                    <li><a href="{% url 'user:address' %}"{% if page == 'address' %}class="active"{% endif %}>· 收货地址</a></li>
                </ul>
            </div>
{#    用户中心右侧内容#}
    {% block right_content %}{% endblock right_content %}
    </div>
{% endblock body %}

templates/list.html
{% extends 'basedetaillist.html' %}
{% block title %}天天生鲜-商品列表{% endblock title %}
{% block main_content %}
	<div class="breadcrumb">
		<a href="#">全部分类</a>
		<span>></span>
		<a href="#">{{ type.name }}</a>
	</div>

	<div class="main_wrap clearfix">
		<div class="l_wrap fl clearfix">
			<div class="new_goods">
				<h3>新品推荐</h3>
				<ul>
                    {% for sku in new_skus %}
					<li>
						<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
						<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
						<div class="prize">￥{{ sku.price }}</div>
					</li>
                    {% endfor %}
				</ul>
			</div>
		</div>

		<div class="r_wrap fr clearfix">
			<div class="sort_bar">
				<a href="{% url 'goods:list' type.id 1 %}" {% if sort == 'default' %}class="active"{% endif %}>默认</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=price" {% if sort == 'price' %}class="active"{% endif %}>价格</a>
				<a href="{% url 'goods:list' type.id 1 %}?sort=hot" {% if sort == 'hot' %}class="active"{% endif %}>人气</a>
			</div>

			<ul class="goods_type_list clearfix">
                {% for sku in skus_page %}
				<li>
					<a href="{% url 'goods:detail' sku.id %}"><img src="{{ sku.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' sku.id %}">{{ sku.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ sku.price }}</span>
						<span class="unit">{{ sku.price}}/{{ sku.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>

			<div class="pagenation">
                {% if skus_page.has_previous %}
				<a href="{% url 'goods:list' type.id skus_page.previous_page_number %}?sort={{ sort }}"><上一页</a>
                {% endif %}
                {% for pindex in pages %}
                    {% if pindex == skus_page.number %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}" class="active">{{ pindex }}</a>
                    {% else %}
				        <a href="{% url 'goods:list' type.id pindex %}?sort={{ sort }}">{{ pindex }}</a>
                    {% endif %}
				{% endfor %}
                {% if skus_page.has_next %}
				<a href="{% url 'goods:list' type.id skus_page.next_page_number %}?sort={{ sort }}">下一页></a>
                {% endif %}
			</div>
		</div>
	</div>
{% endblock main_content %}

templates/place_order.html
{% extends 'basenocart.html' %}
{% load staticfiles %}
{% block title %}天天生鲜-提交订单{% endblock title %}
{% block page_title %}提交订单{% endblock page_title %}
{% block body %}
	<h3 class="common_title">确认收货地址</h3>

	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
            {% for addr in addrs %}
			<dd><input type="radio" name="addr_id" value="{{ addr.id }}" {% if addr.is_default %}checked{% endif %}>{{ addr.addr }} （{{ addr.receiver }} 收） {{ addr.phone }}</dd>
		    {% endfor %}
        </dl>
		<a href="{% url 'user:address' %}" class="edit_site">编辑收货地址</a>

	</div>

	<h3 class="common_title">支付方式</h3>
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" value="1" checked>
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style" value="2">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value="3">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value="4">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>

	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>
		</ul>
        {% for sku in skus %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="{{ sku.image.url }}"></li>
			<li class="col03">{{ sku.name }}</li>
			<li class="col04">{{ sku.unite }}</li>
			<li class="col05">{{ sku.price }}元</li>
			<li class="col06">{{ sku.count }}</li>
			<li class="col07">{{ sku.amount }}元</li>
		</ul>
        {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_count }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>{{ transit_price }}元</b></div>
			<div class="total_pay">实付款：<b>{{ total_pay }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
        {% csrf_token %}
		<a href="javascript:;" sku_ids={{ sku_ids }} id="order_btn">提交订单</a>
	</div>
{% endblock body %}
{% block bottom %}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>

		<div class="mask"></div>
	</div>
{% endblock bottom %}
{% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
            // 获取用户选择的地址id, 支付方式, 要购买的商品id字符串
            addr_id = $('input[name="addr_id"]:checked').val()
            pay_method = $('input[name="pay_style"]:checked').val()
            sku_ids = $(this).attr('sku_ids')
            csrf = $('input[name="csrfmiddlewaretoken"]').val()
            // alert(addr_id+":"+pay_method+':'+sku_ids)
            // 组织参数
            params = {'addr_id':addr_id, 'pay_method':pay_method, 'sku_ids':sku_ids,
                        'csrfmiddlewaretoken':csrf}
            // 发起ajax post请求，访问/order/commit, 传递的参数: addr_id pay_method, sku_ids
            $.post('/order/commit', params, function (data) {
                if (data.res == 5){
                    // 创建成功
                    localStorage.setItem('order_finish',2);
                    $('.popup_con').fadeIn('fast', function() {

                        setTimeout(function(){
                            $('.popup_con').fadeOut('fast',function(){
                                window.location.href = '/user/order/1';
                            });
                        },3000)

                    });
                }
                else{
                    alert(data.errmsg)
                }
            })



		});
	</script>
{% endblock bottomfiles %}

templates/staticbase.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
{%  load staticfiles %}
{#首页  登录 注册#}
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
{#标题块#}
	<title>{%  block title %}{% endblock title %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{#网页顶部引入文件块#}
	{% block topfiles %}{% endblock topfiles %}
</head>
<body>
{#网页顶部欢迎信息块 #}
{% block head_con %}
	<div class="header_con">

		<div class="header">
			<div class="welcome fl">欢迎来到天天生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
					<a href="{%  url 'user:login'%}">登录</a>
					<span>|</span>
					<a href="{%  url 'user:register'%}">注册</a>
				</div>

				<div class="user_link fl">
					<span>|</span>
					<a href="{%  url 'user:user'%}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{%  url 'user:order'%}">我的订单</a>
				</div>
			</div>
		</div>		
	</div>
{%  endblock head_con %}
{#网页顶部搜索框#}
{% block search_bar %}
	<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="images/logo.png"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">1</div>
		</div>
	</div>
{% endblock search_bar %}
{#网页主体内容块#}
{% block body %}{% endblock body %}
	<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{#网页底部html元素块#}
    {% block bottom %}{% endblock bottom %}
{#网页底部代码块#}
    {% block botoomfiles %}{% endblock botoomfiles %}

</body>
</html>

templates/staticindex.html
{% extends 'staticbase.html' %}
{% load staticfiles  %}

	<title>{% block title %}天天生鲜-首页{% endblock title %}</title>
	{% block topfiles %}
        <script type="text/javascript" src="js/jquery-1.12.4.min.js"></script>
        <script type="text/javascript" src="js/jquery-ui.min.js"></script>
        <script type="text/javascript" src="js/slide.js"></script>
    {% endblock topfiles %}





{% block body %}
	<div class="navbar_con">
		<div class="navbar">
			<h1 class="fl">全部商品分类</h1>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>

	<div class="center_con clearfix">
		<ul class="subnav fl">
            {% for type in types %}
			    <li><a href="#model0{{ forloop.counter }}" class="{{ type.logo }}">{{ type.name }}</a></li>
            {% endfor %}
		</ul>
		<div class="slide fl">
			<ul class="slide_pics">
                {% for banner in goods_banners  %}
				    <li><a href="{% url 'goods:detail' banner.sku.id %}"><img src="{{ banner.image.url }}" alt="幻灯片"></a></li>
                {% endfor %}
			</ul>
			<div class="prev"></div>
			<div class="next"></div>
			<ul class="points"></ul>
		</div>
		<div class="adv fl">
            {% for banner in promotion_banners %}
			    <a href="{{ banner.url }}"><img src="{{ banner.image.url }}"></a>
            {% endfor %}
		</div>
	</div>

    {% for type in types %}
	<div class="list_model">
		<div class="list_title clearfix">
			<h3 class="fl" id="model0{{ forloop.counter }}">{{ type.name }}</h3>
			<div class="subtitle fl">
				<span>|</span>
                {% for banner in type.title_banners %}
				    <a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a>
				{% endfor %}
			</div>
			<a href="#" class="goods_more fr" id="fruit_more">查看更多 ></a>
		</div>

		<div class="goods_con clearfix">
			<div class="goods_banner fl"><img src="{{ type.image.url }}"></div>
			<ul class="goods_list fl">
                {% for banner in type.image_banners %}
				<li>
					<h4><a href="{% url 'goods:detail' banner.sku.id  %}">{{ banner.sku.name }}</a></h4>
					<a href="{% url 'goods:detail' banner.sku.id  %}"><img src="{{ banner.sku.image.url }}"></a>
					<div class="prize">¥ {{ banner.sku.price }}</div>
				</li>
				{% endfor %}
			</ul>
		</div>
	</div>
    {% endfor %}
{% endblock body %}

 {% block botoomfiles %}
	<script type="text/javascript" src="js/slideshow.js"></script>
	<script type="text/javascript">
		BCSlideshow('focuspic');
		var oFruit = document.getElementById('fruit_more');
		var oShownum = document.getElementById('show_count');

		var hasorder = localStorage.getItem('order_finish');

		if(hasorder)
		{
			oShownum.innerHTML = '2';
		}

		oFruit.onclick = function(){
			window.location.href = 'list.html';
		}
	</script>
{% endblock botoomfiles %}
</body>
</html>

templates/user_center_info.html
{% extends 'baseusercenter.html' %}
{% load staticfiles %}
{% block right_content %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">

							<li><span>用户名：</span>{{user.username}}</li>
                            {% if address %}
							<li><span>联系方式：</span>{{address.phone}}</li>
							<li><span>联系地址：</span>{{address.addr}}</li>
                            {% else %}
                            <li><span>无默认信息</span></li>
                            {% endif %}
						</ul>
				</div>
				
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for goods in goods_li %}
                            <li>
                                <a href="{% url 'goods:detail' goods.id %}"><img src="{{  goods.imgae.url }}"></a>
                                <h4><a href="{% url 'goods:detail' goods.id %}">{{goods.name}}</a></h4>
                                <div class="operate">
                                    <span class="prize">￥{{goods.price}}</span>
                                    <span class="unit">{{ goods.price }}/{{ goos.unite }}</span>
                                    <a href="#" class="add_goods" title="加入购物车"></a>
                                </div>
                            </li>
                            {% empty %}
                                    无历史浏览记录
                        {% endfor %}


			</ul>
		</div>
		</div>
{% endblock right_content %}